config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  
  devise_for :users

  resources :categories do
    resources :tasks    # associates task to categories
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    belongs_to :user
    has_many :tasks

    validates :cat_name, presence: true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :category
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :categories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [ :show, :edit, :update, :destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @categories = current_user.categories
  end

  def show
    @overdue = @category.tasks.where("due_date < ?", Date.current)
    @today = @category.tasks.where("due_date = ?", Date.current)
    @someday = @category.tasks.where("due_date > ?", Date.current)
  end

  def new
    # @category = Category.new
    @category = current_user.categories.build
  end

  def edit
  end

  def create
    # @category = Category.new(category_params)
    @category = current_user.categories.build(category_params)

    if @category.save
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end

    # Scaffold default

    # respond_to do |format|
    #   if @category.save
    #     format.html { redirect_to category_url(@category), notice: "Category was successfully created." }
    #     format.json { render :show, status: :created, location: @category }
    #   else
    #     format.html { render :new, status: :unprocessable_entity }
    #     format.json { render json: @category.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def update
    if @category.update(category_params)
      redirect_to category_path(@category), notice: "Category was successfully updated."
    else
      render :edit
    end

    # Scaffold default

    # respond_to do |format|
    #   if @category.update(category_params)
    #     format.html { redirect_to category_url(@category), notice: "Category was successfully updated." }
    #     format.json { render :show, status: :ok, location: @category }
    #   else
    #     format.html { render :edit, status: :unprocessable_entity }
    #     format.json { render json: @category.errors, status: :unprocessable_entity }
    #   end
    # end
  end

  def destroy
    @category.destroy

    redirect_to categories_path, notice: "Category was successfully destroyed."

    # Scaffold default

    # respond_to do |format|
    #   format.html { redirect_to categories_url, notice: "Category was successfully destroyed." }
    #   format.json { head :no_content }
    # end
  end

  def correct_user
    @category = current_user.categories.find_by(id: params[:id])
    redirect_to categories_path, notice: "Not Authorized to edit this category" if @category.nil?
  end

  private
    def set_category
      # @category = Category.find(params[:id])                        # Find the category id
      @category = current_user.categories.find_by(id: params[:id])    # With regards to user, find cat id
    end

    def category_params
      params.require(:category).permit(:cat_name, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    before_action :set_category, only: [ :create, :show, :edit, :update, :destroy ]

    def create
        # @category = current_user.categories.find(params[:category_id])
        @task = @category.tasks.create(task_params)
        redirect_to category_path(@category), notice: "Task successfully created"
    end

    def show
        @task = @category.tasks.find(params[:id])
    end

    def edit
        @task = @category.tasks.find(params[:id])
    end

    def update
        @task = @category.tasks.find(params[:id])
        if @task.update(task_params)
            redirect_to category_path(@category), notice: "Task was successfully updated"
        else
            render :edit
        end
    end

    def destroy
        @task = @category.tasks.find(params[:id])
        @task.destroy
        redirect_to @category
    end

    private
        def set_category
            @category = current_user.categories.find(params[:category_id])
        end

        def task_params
            params.require(:task).permit(:task, :comment, :due_date)
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/categories/_form.html.erb
<%= form_with(model: category) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :"Category name:" %>
    <%= form.text_field :cat_name, placeholder:"Grocery, work, chores..." %>
  </div>

  <div class="field">
    <%= form.hidden_field :user_id, value: current_user.id %>
  </div>

  <% if false %>
    <div class="field">
      <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value: current_user.id, type: :hidden %>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div class="container categories-wrapper">
  <div class="container-md categories-header">
    <h1>Categories</h1>
    <span>User Id<span>
    <i class="fa-solid fa-plus"></i>
    <i class="fa-solid fa-house"></i>
    <button class="nav-item">
      <%= link_to '📝', new_category_path, class: "nav-link" %>
    </button>
  </div>

  <% @categories.each do |category| %>
    <div class="container-md category-container">
      <div class="container-sm category-header">
        <h3><%= link_to category.cat_name, category %></h3>
        <button><%= link_to '🗑️', category, method: :delete, data: { confirm: 'You sure?' } %></button>
      </div>
      <ul class="category-details">
        <li>Tasks: <%= category.tasks.length %></li>
        <li>Status:
          <% if category.tasks.detect { |task| task.due_date < Date.current } %>
            <span>🔥 Uh-oh</span>
          <% else %>
            <span>🟢 All Good</span>
          <% end %>
        </li>
      </ul>
    </div>
  <% end %>
</div>






<%# Discarded %>

<% if false %>

<%# scaffold default %>

<p id="notice"><%= notice %></p>

<h1>Categories</h1>

<table class="table">
  <thead>
    <tr>
      <th>Category name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td><%= category.cat_name %></td>
        <td><%= link_to 'Show', category %></td>
        <td><%= link_to 'Edit', edit_category_path(category) %></td>
        <td><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Category', new_category_path %>

<%# Alert icon initial if statement %>

          <% category.tasks.each do |task| %>
            <% if task.due_date < Date.current %>
              <span>🔥</span>
              <% break %>
            <% else %>
              <span><%= task %><%= category.tasks.length %></span>
            <% end %>
          <% end %>

<% end %>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= render 'form', category: @category %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
<h2><strong><%= @category.cat_name %> Tasks</strong></h2>

<h4>Overdue: </h4>
<% @overdue.each do |task| %>
  <%= render 'tasks/task', task: task, category: @category %>
<% end %>

<h4>Due Today: </h4>
<% @today.each do |task| %>
  <%= render 'tasks/task', task: task, category: @category %>
<% end %>

<h4>Due Someday: </h4>
<% @someday.each do |task| %>
  <%= render 'tasks/task', task: task, category: @category %>
<% end %>

<h4>Add task: </h4>
<%= render 'tasks/form' %>

<%= link_to 'Edit', edit_category_path(@category) %> |
<%= link_to 'Back', categories_path %>


<%# Discarded %>

<%# Task content %>

<% if false %>
  <h3>Tasks</h3>
  <h4>Due Today: </h4>
  <%= render @category.tasks %>
  <h4>Due Someday: </h4>
  <% @category.tasks.each do |task| %>
    <% if task.due_date != Date.current %>
        <div class="someday task-bars">
            <div>
                <p>
                    <strong>Task: </strong>
                    <%= task.task %>
                </p>
            </div>
            <p>
                <strong>Due date: </strong>
                <%= task.due_date %>
            </p>
            <ul>
              <li class="task-command"><%= link_to 'Show task', category_task_path(@category, task) %></li>
              <li class="task-command"><%= link_to 'Edit task', edit_category_task_path(@category, task) %></li>
              <li class="task-command"><%= link_to 'Delete Task', [task.category, task], method: :delete, data: { confirm: 'Delete task?' } %></li>
            <ul>
        </div>
    <% end %>
  <% end %>
<% end %>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar">
  <div class="container-fluid">
    <%= link_to 'Metasks', root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse navbar-content-container" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 navbar-content-left">
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to 'Tasks', categories_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to 'New task', new_category_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to 'Edit User', edit_user_registration_path, class: "nav-link" %>
            </li>
        <% end %>  
      </ul>
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 navbar-content-right">
        <% if user_signed_in? %>
            <li class="nav-item">
                <%= link_to current_user.email, edit_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Sign up', new_user_registration_path, class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to 'Log in', new_user_session_path, class: "nav-link" %>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<%# Discarded %>

app/views/home/about.html.erb
<h1>About us</h1>

app/views/home/index.html.erb
<h1>To Do App</h1>
Put something here bro. Maybe login?

app/views/layouts/_alerts.html.erb
<br/>
<div class="alert alert-secondary" role="alert">
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Metasks</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    
    <%# rails default %>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://kit.fontawesome.com/6b1042d8ae.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <div class="container page-wrapper">
      <%= render 'home/header' %>
      <% if notice %>
        <%= render 'layouts/alerts' %>
      <% end %>
      <%= yield %>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
  </body>
</html>



<%# rails default %>
<% if false %>
  <!DOCTYPE html>
  <html>
    <head>
      <title>Todo</title>
      <meta name="viewport" content="width=device-width,initial-scale=1">
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
      <%= yield %>
    </body>
  </html>
<% end %>

app/views/tasks/_form.html.erb
<%= form_with model: [ @category, @category.tasks.build ] do |form| %>
  <p>
    <%= form.label :task %><br>
    <%= form.text_field :task %>
  </p>
  <p>
    <%= form.label :comment %><br>
    <%= form.text_area :comment %>
  </p>
  <p>
    <%= form.label "Due date" %><br>
    <%= form.date_field :due_date %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/tasks/_form2.html.erb
<%= form_with model: [ @category, @task ] do |form| %>
  <p>
    <%= form.label :task %><br>
    <%= form.text_field :task %>
  </p>
  <p>
    <%= form.label :comment %><br>
    <%= form.text_area :comment %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/tasks/_task.html.erb
<div class="task-bars">
    <div>
        <p>
            <strong>Task: </strong>
            <%= task.task %>
        </p>
        <p></p>
    </div>
    <p>
        <strong>Due date: </strong>
        <%= task.due_date %>
    </p>
    <ul>
        <li class="task-command"><%= link_to 'Show task', category_task_path(category, task) %></li>
        <li class="task-command"><%= link_to 'Edit task', edit_category_task_path(category, task) %></li>
        <li class="task-command"><%= link_to 'Delete Task', [task.category, task], method: :delete, data: { confirm: 'Delete task?' } %></li>
    <ul>
</div>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'tasks/form' %>


<%= link_to 'Back', categories_task_path %>

app/views/tasks/show.html.erb
<h3><%= @task.task %></h3>

<div>
    <span>Comment: </span>
    <%= @task.comment %>
</div>

<%= link_to 'Back', @category %>